// filepath: /d:/BackEnd/Admin FoodCommerce/dashboard-adminpanel/Free-Admin-Dashboard/src/pages/index.ts
export { default as Categories } from './Categories';
export { default as SubCategories } from './SubCategories';
export { default as CreateCategory } from './CreateCategory';
export { default as CreateSubCategory } from './CreateSubCategory'
export { default as CreateOrder } from './CreateOrder';
export { default as CreateProduct } from './CreateProduct';
export { default as CreateReview } from './CreateReview';
export { default as CreateUser } from './CreateUser';
export { default as EditCategory } from './EditCategory';
export { default as EditSubCategory } from './EditSubCategory';
export { default as EditOrder } from './EditOrder';
export { default as EditProduct } from './EditProduct';
export { default as EditReview } from './EditReview';
export { default as EditUser } from './EditUser';
export { default as HelpDesk } from './HelpDesk';
export { default as HomeLayout } from './HomeLayout';
export { default as Landing } from './Landing';
export { default as LandingV2 } from './LandingV2';
export { default as Login } from './Login';